# Generated by Django 5.2.3 on 2025-06-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='usrename',
            new_name='username',
        ),
    ]
