# Generated by Django 5.2.3 on 2025-07-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='l_name',
            new_name='username',
        ),
    ]
