# Generated by Django 5.2.3 on 2025-07-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0002_rename_l_name_sign_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='confirm_password',
            field=models.CharField(default='no', max_length=150),
        ),
        migrations.AddField(
            model_name='sign',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('no', 'Prefer not to say')], default='no', max_length=10),
        ),
    ]
