# Generated by Django 5.2.3 on 2025-07-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_page', '0003_sign_confirm_password_sign_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='confirm_password',
        ),
    ]
